### ISSUE TITLE
Script error decompressing Camilladsp binary

### ISSUE THREAD

**Issue by rp86** [HEnquist/camilladsp-setupscripts#12]
Current version of the script on Linux tries to decompress the binary to the working directory of the script, clashing with the camilladsp directory. The following code substitution seems to work correctly, and saves the extra step of moving the binary after decompression. 

```
echo "--- Uncompress CamillaDSP binary"
if [ -f $INSTALL_ROOT/bin/camilladsp ]; then
    echo "Deleting existing camilladsp binary"
    rm $INSTALL_ROOT/bin/camilladsp
fi
tar -xvf $ARCHIVE_NAME -C $INSTALL_ROOT/bin
if [ $? -ne 0 ]; then
    echo "Failed to uncompress binary"
    exit 1
fi
```

**Comment by HEnquist** [comment]
Thanks for the code! I got inspired and also changed the scripts to download to $INSTALL_ROOT/temp instead, to avoid doing anything in the current working dir.
See https://github.com/HEnquist/camilladsp-setupscripts/pull/13/files

**Comment by rp86** [comment]
Fantastic, thanks! I can't test right now but looks like that will do the trick.
