### ISSUE TITLE
Is this currently only available for macOS?

### ISSUE THREAD

**Issue by ElliottDyson** [HEnquist/camilladsp-setupscripts#4]
The text document only describes use with macOS, however the title of the project mentions different platforms. Also, Happy New Year!

**Comment by HEnquist** [comment]
I have only managed to finish the script for macOS so far. The plan is to make scripts for more platforms. Just need more free time!

Happy new year to you too!

**Comment by HEnquist** [comment]
This now works on Linux, Max and Windows :)
