### ISSUE TITLE
Mac Studio M1 - Unsupported CPU type!

### ISSUE THREAD

**Issue by NeighNeighNeigh** [HEnquist/camilladsp-setupscripts#5]
Hello,

When I run the install script, I am thrown the following error: "Unsupported CPU type!". 
This is on a M1 Mac Studio running macOS Monterey Version 12.5.1 (21G83).

Would anyone mind giving me a hand?

**Comment by HEnquist** [comment]
For some reason the cpu type check isn't working. Can you run this in a terminal and post the output?
```sh
uname -m
```

**Comment by NeighNeighNeigh** [comment]
Sure thing, result: `arm64`

**Comment by HEnquist** [comment]
Thanks! The script expects "aarch64", so either the script has been wrong from the start, or the output of uname changed in Monterey. I'll update it. For now you can get past this by editing line 13 in the script:
```
elif [ "$ARCH" == "aarch64" ]
```
Just change "aarch64" to "arm64".

**Comment by NeighNeighNeigh** [comment]
Beautiful that does the trick!
I had to adjust the script a little bit because I opted for minconda instead of anaconda.
So I commented out some of the code and added a line defining 'source' as the conda.sh file in the miniconda path.

```Python
# if [ -f ~/opt/anaconda3/etc/profile.d/conda.sh ]; then
#     echo "Using user conda"
#     source ~/opt/anaconda3/etc/profile.d/conda.sh
# elif [ -f /opt/anaconda3/etc/profile.d/conda.sh ]; then
#     echo "Using system conda"
#     source /opt/anaconda3/etc/profile.d/conda.sh
# else
#     echo "No conda found"
#     exit 1
# fi

source ~/opt/miniconda3/etc/profile.d/conda.sh
```

**Comment by HEnquist** [comment]
Great! And thanks for the reminder about miniconda, I had forgotten about that.
Updated version is here: https://github.com/HEnquist/camilladsp-setupscripts/blob/gui_rc100/install_mac.sh

**Comment by HEnquist** [comment]
Changes merged!
